//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BB_Banka.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KalkulaceEntities : DbContext
    {
        public KalkulaceEntities()
            : base("name=KalkulaceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BROKERI> BROKERI { get; set; }
        public virtual DbSet<KLIENTI> KLIENTI { get; set; }
        public virtual DbSet<KONTAKTY> KONTAKTY { get; set; }
        public virtual DbSet<POZADAVKY> POZADAVKY { get; set; }
    }
}
